/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.lang.reflect.*;

import views.tugas1;
import views.tugas2;
import views.tugas3;


/**
 *
 * @author MAFUD SATRIO SETIONO
 */
public class mainView extends javax.swing.JFrame {

    /**
     * Creates new form mainView
     */
    public mainView() {
        initComponents();
    }
    
    public tugas1 tugas1 = new tugas1();
    public tugas2 tugas2 = new tugas2();
    public tugas3 tugas3 = new tugas3();
    public boolean  isTugas1Exist = false, 
                    isTugas2Exist = false, 
                    isTugas3Exist = false;
        
    // Show menu   
    public void show_menu(String menu)
    {
        hide_menu();
        
        switch(menu) {
            case "tugas1":
                if(!this.isTugas1Exist) {
                    this.isTugas1Exist = true;
                    this.content.add(this.tugas1);
                }
                this.tugas1.setVisible(true);
                break;
            case "tugas2":
                if(!this.isTugas2Exist) {
                    this.isTugas2Exist = true;
                    this.content.add(this.tugas2);
                }
                this.tugas2.setVisible(true);
                break;
            case "tugas3":
                if(!this.isTugas3Exist) {
                    this.isTugas3Exist = true;
                    this.content.add(this.tugas3);
                }
                this.tugas3.setVisible(true);
                break;
        }
    }
    
    // Hide menu    
    public void hide_menu()
    {
        this.tugas1.setVisible(false);
        this.tugas2.setVisible(false);
        this.tugas3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menu_tugas1 = new javax.swing.JMenuItem();
        menu_tugas2 = new javax.swing.JMenuItem();
        menu_tugas3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        menu.add(jMenu1);

        jMenu2.setText("Tugas");

        menu_tugas1.setText("Tugas 1");
        menu_tugas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tugas1ActionPerformed(evt);
            }
        });
        jMenu2.add(menu_tugas1);

        menu_tugas2.setText("Tugas 2");
        menu_tugas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tugas2ActionPerformed(evt);
            }
        });
        jMenu2.add(menu_tugas2);

        menu_tugas3.setText("Tugas 3");
        menu_tugas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tugas3ActionPerformed(evt);
            }
        });
        jMenu2.add(menu_tugas3);

        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_tugas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tugas1ActionPerformed
        show_menu("tugas1");
    }//GEN-LAST:event_menu_tugas1ActionPerformed

    private void menu_tugas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tugas2ActionPerformed
        show_menu("tugas2");
    }//GEN-LAST:event_menu_tugas2ActionPerformed

    private void menu_tugas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tugas3ActionPerformed
        show_menu("tugas3");
    }//GEN-LAST:event_menu_tugas3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane content;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menu_tugas1;
    private javax.swing.JMenuItem menu_tugas2;
    private javax.swing.JMenuItem menu_tugas3;
    // End of variables declaration//GEN-END:variables
}
